// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/v1/prompt.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Visibility defines who can see the template.
type Visibility int32

const (
	Visibility_VISIBILITY_UNSPECIFIED Visibility = 0
	Visibility_VISIBILITY_PRIVATE     Visibility = 1
	Visibility_VISIBILITY_PUBLIC      Visibility = 2
)

// Enum value maps for Visibility.
var (
	Visibility_name = map[int32]string{
		0: "VISIBILITY_UNSPECIFIED",
		1: "VISIBILITY_PRIVATE",
		2: "VISIBILITY_PUBLIC",
	}
	Visibility_value = map[string]int32{
		"VISIBILITY_UNSPECIFIED": 0,
		"VISIBILITY_PRIVATE":     1,
		"VISIBILITY_PUBLIC":      2,
	}
)

func (x Visibility) Enum() *Visibility {
	p := new(Visibility)
	*p = x
	return p
}

func (x Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_prompt_proto_enumTypes[0].Descriptor()
}

func (Visibility) Type() protoreflect.EnumType {
	return &file_api_proto_v1_prompt_proto_enumTypes[0]
}

func (x Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Visibility.Descriptor instead.
func (Visibility) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{0}
}

// TemplateType defines the origin/type of the template.
type TemplateType int32

const (
	TemplateType_TEMPLATE_TYPE_UNSPECIFIED TemplateType = 0
	TemplateType_TEMPLATE_TYPE_SYSTEM      TemplateType = 1
	TemplateType_TEMPLATE_TYPE_USER        TemplateType = 2
)

// Enum value maps for TemplateType.
var (
	TemplateType_name = map[int32]string{
		0: "TEMPLATE_TYPE_UNSPECIFIED",
		1: "TEMPLATE_TYPE_SYSTEM",
		2: "TEMPLATE_TYPE_USER",
	}
	TemplateType_value = map[string]int32{
		"TEMPLATE_TYPE_UNSPECIFIED": 0,
		"TEMPLATE_TYPE_SYSTEM":      1,
		"TEMPLATE_TYPE_USER":        2,
	}
)

func (x TemplateType) Enum() *TemplateType {
	p := new(TemplateType)
	*p = x
	return p
}

func (x TemplateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_prompt_proto_enumTypes[1].Descriptor()
}

func (TemplateType) Type() protoreflect.EnumType {
	return &file_api_proto_v1_prompt_proto_enumTypes[1]
}

func (x TemplateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateType.Descriptor instead.
func (TemplateType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{1}
}

// Template represents a prompt template metadata.
type Template struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the template (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID of the user who owns the template.
	OwnerId string `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// Title of the template.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Description of the template.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Visibility status (public or private).
	Visibility Visibility `protobuf:"varint,5,opt,name=visibility,proto3,enum=v1.Visibility" json:"visibility,omitempty"`
	// Type of the template (system or user).
	Type TemplateType `protobuf:"varint,6,opt,name=type,proto3,enum=v1.TemplateType" json:"type,omitempty"`
	// List of tags associated with the template.
	Tags []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	// Category of the template.
	Category string `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	// List of user IDs who liked the template.
	LikedBy []string `protobuf:"bytes,9,rep,name=liked_by,json=likedBy,proto3" json:"liked_by,omitempty"`
	// List of user IDs who favorited the template.
	FavoritedBy []string `protobuf:"bytes,10,rep,name=favorited_by,json=favoritedBy,proto3" json:"favorited_by,omitempty"`
	// Timestamp when the template was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp when the template was last updated.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// The latest version of the template.
	LatestVersion *TemplateVersion `protobuf:"bytes,13,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{0}
}

func (x *Template) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Template) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Template) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Template) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Template) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_VISIBILITY_UNSPECIFIED
}

func (x *Template) GetType() TemplateType {
	if x != nil {
		return x.Type
	}
	return TemplateType_TEMPLATE_TYPE_UNSPECIFIED
}

func (x *Template) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Template) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Template) GetLikedBy() []string {
	if x != nil {
		return x.LikedBy
	}
	return nil
}

func (x *Template) GetFavoritedBy() []string {
	if x != nil {
		return x.FavoritedBy
	}
	return nil
}

func (x *Template) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Template) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Template) GetLatestVersion() *TemplateVersion {
	if x != nil {
		return x.LatestVersion
	}
	return nil
}

// TemplateVersion represents a specific version of a template's content.
type TemplateVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the version record.
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID of the parent template.
	TemplateId string `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// Logical version number (1, 2, 3...).
	Version int32 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// The actual prompt content with placeholders (e.g., $$).
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// Timestamp when this version was created.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateVersion) Reset() {
	*x = TemplateVersion{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateVersion) ProtoMessage() {}

func (x *TemplateVersion) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateVersion.ProtoReflect.Descriptor instead.
func (*TemplateVersion) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{1}
}

func (x *TemplateVersion) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TemplateVersion) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *TemplateVersion) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TemplateVersion) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TemplateVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ListTemplateVersionsRequest is the request message for ListTemplateVersions.
type ListTemplateVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplateVersionsRequest) Reset() {
	*x = ListTemplateVersionsRequest{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplateVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplateVersionsRequest) ProtoMessage() {}

func (x *ListTemplateVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplateVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListTemplateVersionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{2}
}

func (x *ListTemplateVersionsRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *ListTemplateVersionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTemplateVersionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListTemplateVersionsResponse is the response message for ListTemplateVersions.
type ListTemplateVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*TemplateVersion     `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplateVersionsResponse) Reset() {
	*x = ListTemplateVersionsResponse{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplateVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplateVersionsResponse) ProtoMessage() {}

func (x *ListTemplateVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplateVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListTemplateVersionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{3}
}

func (x *ListTemplateVersionsResponse) GetVersions() []*TemplateVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ListTemplateVersionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Prompt represents an instantiated prompt saved by a user.
type Prompt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the prompt (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID of the template used.
	TemplateId string `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// ID of the specific version used.
	VersionId int32 `protobuf:"varint,3,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	// ID of the user who saved this prompt.
	OwnerId string `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// List of variable values used to replace placeholders.
	Variables []string `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty"`
	// Timestamp when the prompt was created.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prompt) Reset() {
	*x = Prompt{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prompt) ProtoMessage() {}

func (x *Prompt) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prompt.ProtoReflect.Descriptor instead.
func (*Prompt) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{4}
}

func (x *Prompt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Prompt) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *Prompt) GetVersionId() int32 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *Prompt) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Prompt) GetVariables() []string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *Prompt) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// CreateTemplateRequest is the request message for CreateTemplate.
type CreateTemplateRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	OwnerId     string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Visibility  Visibility             `protobuf:"varint,4,opt,name=visibility,proto3,enum=v1.Visibility" json:"visibility,omitempty"`
	Type        TemplateType           `protobuf:"varint,5,opt,name=type,proto3,enum=v1.TemplateType" json:"type,omitempty"`
	Tags        []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Category    string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	// Initial content for the first version.
	Content       string `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTemplateRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateTemplateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTemplateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTemplateRequest) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_VISIBILITY_UNSPECIFIED
}

func (x *CreateTemplateRequest) GetType() TemplateType {
	if x != nil {
		return x.Type
	}
	return TemplateType_TEMPLATE_TYPE_UNSPECIFIED
}

func (x *CreateTemplateRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateTemplateRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateTemplateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// CreateTemplateResponse is the response message for CreateTemplate.
type CreateTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *Template              `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Version       *TemplateVersion       `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateResponse) Reset() {
	*x = CreateTemplateResponse{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateResponse) ProtoMessage() {}

func (x *CreateTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateResponse.ProtoReflect.Descriptor instead.
func (*CreateTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTemplateResponse) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *CreateTemplateResponse) GetVersion() *TemplateVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

// UpdateTemplateRequest is the request message for UpdateTemplate.
type UpdateTemplateRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TemplateId  string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	OwnerId     string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"` // For authorization check
	Title       string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Visibility  Visibility             `protobuf:"varint,5,opt,name=visibility,proto3,enum=v1.Visibility" json:"visibility,omitempty"`
	Tags        []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Category    string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	// New content, which triggers a new version creation.
	Content       string `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateRequest) Reset() {
	*x = UpdateTemplateRequest{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateRequest) ProtoMessage() {}

func (x *UpdateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *UpdateTemplateRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *UpdateTemplateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTemplateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTemplateRequest) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_VISIBILITY_UNSPECIFIED
}

func (x *UpdateTemplateRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateTemplateRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateTemplateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// UpdateTemplateResponse is the response message for UpdateTemplate.
type UpdateTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *Template              `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	NewVersion    *TemplateVersion       `protobuf:"bytes,2,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateResponse) Reset() {
	*x = UpdateTemplateResponse{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateResponse) ProtoMessage() {}

func (x *UpdateTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateResponse.ProtoReflect.Descriptor instead.
func (*UpdateTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTemplateResponse) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *UpdateTemplateResponse) GetNewVersion() *TemplateVersion {
	if x != nil {
		return x.NewVersion
	}
	return nil
}

// GetTemplateRequest is the request message for GetTemplate.
type GetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateRequest) Reset() {
	*x = GetTemplateRequest{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRequest) ProtoMessage() {}

func (x *GetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{9}
}

func (x *GetTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetTemplateResponse is the response message for GetTemplate.
type GetTemplateResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Template *Template              `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	// Optionally return the latest version or all versions.
	// For simplicity, let's return the latest version.
	LatestVersion *TemplateVersion `protobuf:"bytes,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateResponse) Reset() {
	*x = GetTemplateResponse{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateResponse) ProtoMessage() {}

func (x *GetTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateResponse.ProtoReflect.Descriptor instead.
func (*GetTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{10}
}

func (x *GetTemplateResponse) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *GetTemplateResponse) GetLatestVersion() *TemplateVersion {
	if x != nil {
		return x.LatestVersion
	}
	return nil
}

// ListTemplatesRequest is the request message for ListTemplates.
type ListTemplatesRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PageSize  int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Filter by visibility (e.g., public only, or my private ones).
	Visibility Visibility `protobuf:"varint,3,opt,name=visibility,proto3,enum=v1.Visibility" json:"visibility,omitempty"`
	// Filter by owner.
	OwnerId string `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// Filter by category.
	Category string `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	// Filter by tags.
	Tags          []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{11}
}

func (x *ListTemplatesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTemplatesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListTemplatesRequest) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_VISIBILITY_UNSPECIFIED
}

func (x *ListTemplatesRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ListTemplatesRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListTemplatesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// ListTemplatesResponse is the response message for ListTemplates.
type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*Template            `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{12}
}

func (x *ListTemplatesResponse) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListTemplatesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// DeleteTemplateRequest is the request message for DeleteTemplate.
type DeleteTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"` // For auth
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateRequest) Reset() {
	*x = DeleteTemplateRequest{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateRequest) ProtoMessage() {}

func (x *DeleteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteTemplateRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

// DeleteTemplateResponse is the response message for DeleteTemplate.
type DeleteTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateResponse) Reset() {
	*x = DeleteTemplateResponse{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateResponse) ProtoMessage() {}

func (x *DeleteTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateResponse.ProtoReflect.Descriptor instead.
func (*DeleteTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteTemplateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// CreatePromptRequest is the request message for CreatePrompt.
type CreatePromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	VersionId     int32                  `protobuf:"varint,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Variables     []string               `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePromptRequest) Reset() {
	*x = CreatePromptRequest{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePromptRequest) ProtoMessage() {}

func (x *CreatePromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePromptRequest.ProtoReflect.Descriptor instead.
func (*CreatePromptRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{15}
}

func (x *CreatePromptRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreatePromptRequest) GetVersionId() int32 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *CreatePromptRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreatePromptRequest) GetVariables() []string {
	if x != nil {
		return x.Variables
	}
	return nil
}

// CreatePromptResponse is the response message for CreatePrompt.
type CreatePromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        *Prompt                `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePromptResponse) Reset() {
	*x = CreatePromptResponse{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePromptResponse) ProtoMessage() {}

func (x *CreatePromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePromptResponse.ProtoReflect.Descriptor instead.
func (*CreatePromptResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{16}
}

func (x *CreatePromptResponse) GetPrompt() *Prompt {
	if x != nil {
		return x.Prompt
	}
	return nil
}

// GetPromptRequest is the request message for GetPrompt.
type GetPromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromptRequest) Reset() {
	*x = GetPromptRequest{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromptRequest) ProtoMessage() {}

func (x *GetPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromptRequest.ProtoReflect.Descriptor instead.
func (*GetPromptRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{17}
}

func (x *GetPromptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetPromptResponse is the response message for GetPrompt.
type GetPromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        *Prompt                `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromptResponse) Reset() {
	*x = GetPromptResponse{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromptResponse) ProtoMessage() {}

func (x *GetPromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromptResponse.ProtoReflect.Descriptor instead.
func (*GetPromptResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{18}
}

func (x *GetPromptResponse) GetPrompt() *Prompt {
	if x != nil {
		return x.Prompt
	}
	return nil
}

// ListPromptsRequest is the request message for ListPrompts.
type ListPromptsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PageSize  int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OwnerId   string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// Filter by template_id.
	TemplateId    string `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPromptsRequest) Reset() {
	*x = ListPromptsRequest{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPromptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromptsRequest) ProtoMessage() {}

func (x *ListPromptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromptsRequest.ProtoReflect.Descriptor instead.
func (*ListPromptsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{19}
}

func (x *ListPromptsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPromptsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListPromptsRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ListPromptsRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

// ListPromptsResponse is the response message for ListPrompts.
type ListPromptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompts       []*Prompt              `protobuf:"bytes,1,rep,name=prompts,proto3" json:"prompts,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPromptsResponse) Reset() {
	*x = ListPromptsResponse{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPromptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromptsResponse) ProtoMessage() {}

func (x *ListPromptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromptsResponse.ProtoReflect.Descriptor instead.
func (*ListPromptsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{20}
}

func (x *ListPromptsResponse) GetPrompts() []*Prompt {
	if x != nil {
		return x.Prompts
	}
	return nil
}

func (x *ListPromptsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// DeletePromptRequest is the request message for DeletePrompt.
type DeletePromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"` // For auth
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePromptRequest) Reset() {
	*x = DeletePromptRequest{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePromptRequest) ProtoMessage() {}

func (x *DeletePromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePromptRequest.ProtoReflect.Descriptor instead.
func (*DeletePromptRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{21}
}

func (x *DeletePromptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeletePromptRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

// DeletePromptResponse is the response message for DeletePrompt.
type DeletePromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePromptResponse) Reset() {
	*x = DeletePromptResponse{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePromptResponse) ProtoMessage() {}

func (x *DeletePromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePromptResponse.ProtoReflect.Descriptor instead.
func (*DeletePromptResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{22}
}

func (x *DeletePromptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// RegisterRequest is the request message for Register.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	DisplayName   string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{23}
}

func (x *RegisterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// RegisterResponse is the response message for Register.
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // JWT token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{24}
}

func (x *RegisterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// LoginRequest is the request message for Login.
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"` // Or mobile/id
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{25}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginResponse is the response message for Login.
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{26}
}

func (x *LoginResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// LoginWithOAuthRequest is the request message for LoginWithOAuth.
type LoginWithOAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginWithOAuthRequest) Reset() {
	*x = LoginWithOAuthRequest{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithOAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithOAuthRequest) ProtoMessage() {}

func (x *LoginWithOAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithOAuthRequest.ProtoReflect.Descriptor instead.
func (*LoginWithOAuthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{27}
}

func (x *LoginWithOAuthRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LoginWithOAuthRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// ListCategoriesRequest is the request message for ListCategories.
type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{28}
}

// CategoryStats represents a category and its usage count.
type CategoryStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryStats) Reset() {
	*x = CategoryStats{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryStats) ProtoMessage() {}

func (x *CategoryStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryStats.ProtoReflect.Descriptor instead.
func (*CategoryStats) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{29}
}

func (x *CategoryStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryStats) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// ListCategoriesResponse is the response message for ListCategories.
type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CategoryStats       `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{30}
}

func (x *ListCategoriesResponse) GetCategories() []*CategoryStats {
	if x != nil {
		return x.Categories
	}
	return nil
}

// ListTagsRequest is the request message for ListTags.
type ListTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsRequest) Reset() {
	*x = ListTagsRequest{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsRequest) ProtoMessage() {}

func (x *ListTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsRequest.ProtoReflect.Descriptor instead.
func (*ListTagsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{31}
}

// TagStats represents a tag and its usage count.
type TagStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagStats) Reset() {
	*x = TagStats{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagStats) ProtoMessage() {}

func (x *TagStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagStats.ProtoReflect.Descriptor instead.
func (*TagStats) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{32}
}

func (x *TagStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagStats) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// ListTagsResponse is the response message for ListTags.
type ListTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*TagStats            `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResponse) Reset() {
	*x = ListTagsResponse{}
	mi := &file_api_proto_v1_prompt_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResponse) ProtoMessage() {}

func (x *ListTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_prompt_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResponse.ProtoReflect.Descriptor instead.
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_prompt_proto_rawDescGZIP(), []int{33}
}

func (x *ListTagsResponse) GetTags() []*TagStats {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_api_proto_v1_prompt_proto protoreflect.FileDescriptor

const file_api_proto_v1_prompt_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/v1/prompt.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x03\n" +
	"\bTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12.\n" +
	"\n" +
	"visibility\x18\x05 \x01(\x0e2\x0e.v1.VisibilityR\n" +
	"visibility\x12$\n" +
	"\x04type\x18\x06 \x01(\x0e2\x10.v1.TemplateTypeR\x04type\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x1a\n" +
	"\bcategory\x18\b \x01(\tR\bcategory\x12\x19\n" +
	"\bliked_by\x18\t \x03(\tR\alikedBy\x12!\n" +
	"\ffavorited_by\x18\n" +
	" \x03(\tR\vfavoritedBy\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12:\n" +
	"\x0elatest_version\x18\r \x01(\v2\x13.v1.TemplateVersionR\rlatestVersion\"\xb1\x01\n" +
	"\x0fTemplateVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"z\n" +
	"\x1bListTemplateVersionsRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"w\n" +
	"\x1cListTemplateVersionsResponse\x12/\n" +
	"\bversions\x18\x01 \x03(\v2\x13.v1.TemplateVersionR\bversions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xcc\x01\n" +
	"\x06Prompt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x03 \x01(\x05R\tversionId\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x12\x1c\n" +
	"\tvariables\x18\x05 \x03(\tR\tvariables\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8a\x02\n" +
	"\x15CreateTemplateRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12.\n" +
	"\n" +
	"visibility\x18\x04 \x01(\x0e2\x0e.v1.VisibilityR\n" +
	"visibility\x12$\n" +
	"\x04type\x18\x05 \x01(\x0e2\x10.v1.TemplateTypeR\x04type\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\"q\n" +
	"\x16CreateTemplateResponse\x12(\n" +
	"\btemplate\x18\x01 \x01(\v2\f.v1.TemplateR\btemplate\x12-\n" +
	"\aversion\x18\x02 \x01(\v2\x13.v1.TemplateVersionR\aversion\"\x85\x02\n" +
	"\x15UpdateTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12.\n" +
	"\n" +
	"visibility\x18\x05 \x01(\x0e2\x0e.v1.VisibilityR\n" +
	"visibility\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\"x\n" +
	"\x16UpdateTemplateResponse\x12(\n" +
	"\btemplate\x18\x01 \x01(\v2\f.v1.TemplateR\btemplate\x124\n" +
	"\vnew_version\x18\x02 \x01(\v2\x13.v1.TemplateVersionR\n" +
	"newVersion\"$\n" +
	"\x12GetTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"{\n" +
	"\x13GetTemplateResponse\x12(\n" +
	"\btemplate\x18\x01 \x01(\v2\f.v1.TemplateR\btemplate\x12:\n" +
	"\x0elatest_version\x18\x02 \x01(\v2\x13.v1.TemplateVersionR\rlatestVersion\"\xcd\x01\n" +
	"\x14ListTemplatesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12.\n" +
	"\n" +
	"visibility\x18\x03 \x01(\x0e2\x0e.v1.VisibilityR\n" +
	"visibility\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\"k\n" +
	"\x15ListTemplatesResponse\x12*\n" +
	"\ttemplates\x18\x01 \x03(\v2\f.v1.TemplateR\ttemplates\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"B\n" +
	"\x15DeleteTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\"2\n" +
	"\x16DeleteTemplateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8e\x01\n" +
	"\x13CreatePromptRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\x05R\tversionId\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x1c\n" +
	"\tvariables\x18\x04 \x03(\tR\tvariables\":\n" +
	"\x14CreatePromptResponse\x12\"\n" +
	"\x06prompt\x18\x01 \x01(\v2\n" +
	".v1.PromptR\x06prompt\"\"\n" +
	"\x10GetPromptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x11GetPromptResponse\x12\"\n" +
	"\x06prompt\x18\x01 \x01(\v2\n" +
	".v1.PromptR\x06prompt\"\x8c\x01\n" +
	"\x12ListPromptsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x1f\n" +
	"\vtemplate_id\x18\x04 \x01(\tR\n" +
	"templateId\"c\n" +
	"\x13ListPromptsResponse\x12$\n" +
	"\aprompts\x18\x01 \x03(\v2\n" +
	".v1.PromptR\aprompts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"@\n" +
	"\x13DeletePromptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\"0\n" +
	"\x14DeletePromptResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8e\x01\n" +
	"\x0fRegisterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\"8\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"X\n" +
	"\rLoginResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"G\n" +
	"\x15LoginWithOAuthRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\x17\n" +
	"\x15ListCategoriesRequest\"9\n" +
	"\rCategoryStats\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"K\n" +
	"\x16ListCategoriesResponse\x121\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x11.v1.CategoryStatsR\n" +
	"categories\"\x11\n" +
	"\x0fListTagsRequest\"4\n" +
	"\bTagStats\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"4\n" +
	"\x10ListTagsResponse\x12 \n" +
	"\x04tags\x18\x01 \x03(\v2\f.v1.TagStatsR\x04tags*W\n" +
	"\n" +
	"Visibility\x12\x1a\n" +
	"\x16VISIBILITY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12VISIBILITY_PRIVATE\x10\x01\x12\x15\n" +
	"\x11VISIBILITY_PUBLIC\x10\x02*_\n" +
	"\fTemplateType\x12\x1d\n" +
	"\x19TEMPLATE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TEMPLATE_TYPE_SYSTEM\x10\x01\x12\x16\n" +
	"\x12TEMPLATE_TYPE_USER\x10\x022\xb2\x01\n" +
	"\vUserService\x125\n" +
	"\bRegister\x12\x13.v1.RegisterRequest\x1a\x14.v1.RegisterResponse\x12,\n" +
	"\x05Login\x12\x10.v1.LoginRequest\x1a\x11.v1.LoginResponse\x12>\n" +
	"\x0eLoginWithOAuth\x12\x19.v1.LoginWithOAuthRequest\x1a\x11.v1.LoginResponse2\x8b\x06\n" +
	"\rPromptService\x12G\n" +
	"\x0eCreateTemplate\x12\x19.v1.CreateTemplateRequest\x1a\x1a.v1.CreateTemplateResponse\x12G\n" +
	"\x0eUpdateTemplate\x12\x19.v1.UpdateTemplateRequest\x1a\x1a.v1.UpdateTemplateResponse\x12>\n" +
	"\vGetTemplate\x12\x16.v1.GetTemplateRequest\x1a\x17.v1.GetTemplateResponse\x12D\n" +
	"\rListTemplates\x12\x18.v1.ListTemplatesRequest\x1a\x19.v1.ListTemplatesResponse\x12G\n" +
	"\x0eDeleteTemplate\x12\x19.v1.DeleteTemplateRequest\x1a\x1a.v1.DeleteTemplateResponse\x12A\n" +
	"\fCreatePrompt\x12\x17.v1.CreatePromptRequest\x1a\x18.v1.CreatePromptResponse\x128\n" +
	"\tGetPrompt\x12\x14.v1.GetPromptRequest\x1a\x15.v1.GetPromptResponse\x12A\n" +
	"\fDeletePrompt\x12\x17.v1.DeletePromptRequest\x1a\x18.v1.DeletePromptResponse\x12G\n" +
	"\x0eListCategories\x12\x19.v1.ListCategoriesRequest\x1a\x1a.v1.ListCategoriesResponse\x125\n" +
	"\bListTags\x12\x13.v1.ListTagsRequest\x1a\x14.v1.ListTagsResponse\x12Y\n" +
	"\x14ListTemplateVersions\x12\x1f.v1.ListTemplateVersionsRequest\x1a .v1.ListTemplateVersionsResponseB'Z%awsome-prompt/backend/api/proto/v1;v1b\x06proto3"

var (
	file_api_proto_v1_prompt_proto_rawDescOnce sync.Once
	file_api_proto_v1_prompt_proto_rawDescData []byte
)

func file_api_proto_v1_prompt_proto_rawDescGZIP() []byte {
	file_api_proto_v1_prompt_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_prompt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_prompt_proto_rawDesc), len(file_api_proto_v1_prompt_proto_rawDesc)))
	})
	return file_api_proto_v1_prompt_proto_rawDescData
}

var file_api_proto_v1_prompt_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_v1_prompt_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_api_proto_v1_prompt_proto_goTypes = []any{
	(Visibility)(0),                      // 0: v1.Visibility
	(TemplateType)(0),                    // 1: v1.TemplateType
	(*Template)(nil),                     // 2: v1.Template
	(*TemplateVersion)(nil),              // 3: v1.TemplateVersion
	(*ListTemplateVersionsRequest)(nil),  // 4: v1.ListTemplateVersionsRequest
	(*ListTemplateVersionsResponse)(nil), // 5: v1.ListTemplateVersionsResponse
	(*Prompt)(nil),                       // 6: v1.Prompt
	(*CreateTemplateRequest)(nil),        // 7: v1.CreateTemplateRequest
	(*CreateTemplateResponse)(nil),       // 8: v1.CreateTemplateResponse
	(*UpdateTemplateRequest)(nil),        // 9: v1.UpdateTemplateRequest
	(*UpdateTemplateResponse)(nil),       // 10: v1.UpdateTemplateResponse
	(*GetTemplateRequest)(nil),           // 11: v1.GetTemplateRequest
	(*GetTemplateResponse)(nil),          // 12: v1.GetTemplateResponse
	(*ListTemplatesRequest)(nil),         // 13: v1.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),        // 14: v1.ListTemplatesResponse
	(*DeleteTemplateRequest)(nil),        // 15: v1.DeleteTemplateRequest
	(*DeleteTemplateResponse)(nil),       // 16: v1.DeleteTemplateResponse
	(*CreatePromptRequest)(nil),          // 17: v1.CreatePromptRequest
	(*CreatePromptResponse)(nil),         // 18: v1.CreatePromptResponse
	(*GetPromptRequest)(nil),             // 19: v1.GetPromptRequest
	(*GetPromptResponse)(nil),            // 20: v1.GetPromptResponse
	(*ListPromptsRequest)(nil),           // 21: v1.ListPromptsRequest
	(*ListPromptsResponse)(nil),          // 22: v1.ListPromptsResponse
	(*DeletePromptRequest)(nil),          // 23: v1.DeletePromptRequest
	(*DeletePromptResponse)(nil),         // 24: v1.DeletePromptResponse
	(*RegisterRequest)(nil),              // 25: v1.RegisterRequest
	(*RegisterResponse)(nil),             // 26: v1.RegisterResponse
	(*LoginRequest)(nil),                 // 27: v1.LoginRequest
	(*LoginResponse)(nil),                // 28: v1.LoginResponse
	(*LoginWithOAuthRequest)(nil),        // 29: v1.LoginWithOAuthRequest
	(*ListCategoriesRequest)(nil),        // 30: v1.ListCategoriesRequest
	(*CategoryStats)(nil),                // 31: v1.CategoryStats
	(*ListCategoriesResponse)(nil),       // 32: v1.ListCategoriesResponse
	(*ListTagsRequest)(nil),              // 33: v1.ListTagsRequest
	(*TagStats)(nil),                     // 34: v1.TagStats
	(*ListTagsResponse)(nil),             // 35: v1.ListTagsResponse
	(*timestamppb.Timestamp)(nil),        // 36: google.protobuf.Timestamp
}
var file_api_proto_v1_prompt_proto_depIdxs = []int32{
	0,  // 0: v1.Template.visibility:type_name -> v1.Visibility
	1,  // 1: v1.Template.type:type_name -> v1.TemplateType
	36, // 2: v1.Template.created_at:type_name -> google.protobuf.Timestamp
	36, // 3: v1.Template.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 4: v1.Template.latest_version:type_name -> v1.TemplateVersion
	36, // 5: v1.TemplateVersion.created_at:type_name -> google.protobuf.Timestamp
	3,  // 6: v1.ListTemplateVersionsResponse.versions:type_name -> v1.TemplateVersion
	36, // 7: v1.Prompt.created_at:type_name -> google.protobuf.Timestamp
	0,  // 8: v1.CreateTemplateRequest.visibility:type_name -> v1.Visibility
	1,  // 9: v1.CreateTemplateRequest.type:type_name -> v1.TemplateType
	2,  // 10: v1.CreateTemplateResponse.template:type_name -> v1.Template
	3,  // 11: v1.CreateTemplateResponse.version:type_name -> v1.TemplateVersion
	0,  // 12: v1.UpdateTemplateRequest.visibility:type_name -> v1.Visibility
	2,  // 13: v1.UpdateTemplateResponse.template:type_name -> v1.Template
	3,  // 14: v1.UpdateTemplateResponse.new_version:type_name -> v1.TemplateVersion
	2,  // 15: v1.GetTemplateResponse.template:type_name -> v1.Template
	3,  // 16: v1.GetTemplateResponse.latest_version:type_name -> v1.TemplateVersion
	0,  // 17: v1.ListTemplatesRequest.visibility:type_name -> v1.Visibility
	2,  // 18: v1.ListTemplatesResponse.templates:type_name -> v1.Template
	6,  // 19: v1.CreatePromptResponse.prompt:type_name -> v1.Prompt
	6,  // 20: v1.GetPromptResponse.prompt:type_name -> v1.Prompt
	6,  // 21: v1.ListPromptsResponse.prompts:type_name -> v1.Prompt
	31, // 22: v1.ListCategoriesResponse.categories:type_name -> v1.CategoryStats
	34, // 23: v1.ListTagsResponse.tags:type_name -> v1.TagStats
	25, // 24: v1.UserService.Register:input_type -> v1.RegisterRequest
	27, // 25: v1.UserService.Login:input_type -> v1.LoginRequest
	29, // 26: v1.UserService.LoginWithOAuth:input_type -> v1.LoginWithOAuthRequest
	7,  // 27: v1.PromptService.CreateTemplate:input_type -> v1.CreateTemplateRequest
	9,  // 28: v1.PromptService.UpdateTemplate:input_type -> v1.UpdateTemplateRequest
	11, // 29: v1.PromptService.GetTemplate:input_type -> v1.GetTemplateRequest
	13, // 30: v1.PromptService.ListTemplates:input_type -> v1.ListTemplatesRequest
	15, // 31: v1.PromptService.DeleteTemplate:input_type -> v1.DeleteTemplateRequest
	17, // 32: v1.PromptService.CreatePrompt:input_type -> v1.CreatePromptRequest
	19, // 33: v1.PromptService.GetPrompt:input_type -> v1.GetPromptRequest
	23, // 34: v1.PromptService.DeletePrompt:input_type -> v1.DeletePromptRequest
	30, // 35: v1.PromptService.ListCategories:input_type -> v1.ListCategoriesRequest
	33, // 36: v1.PromptService.ListTags:input_type -> v1.ListTagsRequest
	4,  // 37: v1.PromptService.ListTemplateVersions:input_type -> v1.ListTemplateVersionsRequest
	26, // 38: v1.UserService.Register:output_type -> v1.RegisterResponse
	28, // 39: v1.UserService.Login:output_type -> v1.LoginResponse
	28, // 40: v1.UserService.LoginWithOAuth:output_type -> v1.LoginResponse
	8,  // 41: v1.PromptService.CreateTemplate:output_type -> v1.CreateTemplateResponse
	10, // 42: v1.PromptService.UpdateTemplate:output_type -> v1.UpdateTemplateResponse
	12, // 43: v1.PromptService.GetTemplate:output_type -> v1.GetTemplateResponse
	14, // 44: v1.PromptService.ListTemplates:output_type -> v1.ListTemplatesResponse
	16, // 45: v1.PromptService.DeleteTemplate:output_type -> v1.DeleteTemplateResponse
	18, // 46: v1.PromptService.CreatePrompt:output_type -> v1.CreatePromptResponse
	20, // 47: v1.PromptService.GetPrompt:output_type -> v1.GetPromptResponse
	24, // 48: v1.PromptService.DeletePrompt:output_type -> v1.DeletePromptResponse
	32, // 49: v1.PromptService.ListCategories:output_type -> v1.ListCategoriesResponse
	35, // 50: v1.PromptService.ListTags:output_type -> v1.ListTagsResponse
	5,  // 51: v1.PromptService.ListTemplateVersions:output_type -> v1.ListTemplateVersionsResponse
	38, // [38:52] is the sub-list for method output_type
	24, // [24:38] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_api_proto_v1_prompt_proto_init() }
func file_api_proto_v1_prompt_proto_init() {
	if File_api_proto_v1_prompt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_prompt_proto_rawDesc), len(file_api_proto_v1_prompt_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_v1_prompt_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_prompt_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_prompt_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_prompt_proto_msgTypes,
	}.Build()
	File_api_proto_v1_prompt_proto = out.File
	file_api_proto_v1_prompt_proto_goTypes = nil
	file_api_proto_v1_prompt_proto_depIdxs = nil
}
